
experiment: experiment1         #[experiment1, experiment2, experiment3, experiment4a, experiment4b, experiment5]
run: run0                       #[run0, run1, run2, run3, run4]
embedding_network: densenet201  #[densenet201, resnet101]

seeds:
  run0: 14
  run1: 123
  run2: 666
  run3: 375
  run4: 693

io_root: ./outputs
weight_dir: ./weights

anom_threshold: 0.5

#### Parameters for trainings
num_workers: 10
max_epoch: 70
bs: 5
lam: 0.5

#### tasks
tasks:
  metaseg_train: False
  metaseg_test: False
  metaseg_visualize: False
  compute_embeddings: False
  detect_clusters: False
  extend_model: False
  infer_validation_data: False

#### datasets
cityscapes:
  _target_: src.datasets.cityscapes.Cityscapes
  root: /home/datasets/cityscapes

cityscapes_human:
  _target_: src.datasets.cityscapes_human.Cityscapes
  root: /home/datasets/cityscapes

cityscapes_bus:
  _target_: src.datasets.cityscapes_bus.Cityscapes
  root:  /home/datasets/cityscapes

cityscapes_human_bus_car:
  _target_: src.datasets.cityscapes_human_bus_car.Cityscapes
  root: /home/datasets/cityscapes


a2d2:
  _target_: src.datasets.a2d2.A2D2
  root: /home/datasets/A2D2


#### models
deeplabv3plus_1:
  _target_: src.models.deepv3.DeepWV3Plus
  num_classes: 17

deeplabv3plus_2:
  _target_: src.models.deepv3.DeepWV3Plus
  num_classes: 18

deeplabv3plus_3a:
  _target_: src.models.deepv3.DeepWV3Plus
  num_classes: 19

deeplabv3plus_4:
  _target_: src.models.deepv3.DeepWV3Plus
  num_classes: 19

deeplabv3plus_5:
  _target_: src.models.deepv3.DeepWV3Plus
  num_classes: 15

pspnet_3b:
  _target_: src.models.pspnet.PSPNet
  num_classes: 19

extended_layers:
  deeplabv3plus_1: ['module.final.6.weight']
  deeplabv3plus_2: ['module.final.6.weight']
  deeplabv3plus_3a: ['module.final.6.weight']
  deeplabv3plus_4: ['module.final.6.weight']
  deeplabv3plus_5: ['module.final.6.weight']
  pspnet_3b: ['module.cls.4.weight', 'module.cls.4.bias', 'module.aux.4.weight', 'module.aux.4.bias']

trainable_layers:
  deeplabv3plus_1: ['final', 'bot']
  deeplabv3plus_2: ['final', 'bot']
  deeplabv3plus_3a: ['final', 'bot']
  deeplabv3plus_4: ['final', 'bot']
  deeplabv3plus_5: ['final', 'bot']
  pspnet_3b: ['cls', 'ppm']

### meta models
gradient_boosting_1:
  weights: meta/booster_cs_human.pickle.dat

gradient_boosting_2:
  weights: meta/booster_cs_bus.pickle.dat

gradient_boosting_3a:
  weights: meta/booster_a2d2_3a.pickle.dat

gradient_boosting_3b:
  weights: meta/booster_a2d2_splits_psp.pickle.dat

gradient_boosting_4:
  weights: meta/booster.pickle.dat

gradient_boosting_5:
  weights: meta/booster_cs_15.pickle.dat

### embedding networks
densenet201:
  _target_: src.models.embedding_networks.feature_densenet201

resnet101:
  _target_: src.models.embedding_networks.feature_resnet101


#### experimental setup
experiments:
  experiment1:
    dataset: cityscapes_human
    split: test
    train_dataset: cityscapes_human
    train_split: train
    dict: experiment1_data.p
    model: deeplabv3plus_1
    init_weights: initials/experiment1/best.pth
    meta_model: gradient_boosting_1
    pred_class_selection: [
        # 0,  # road
        # 1,  # sidewalk
        # 2,  # building
        3,  # wall
        4,  # fence
        # 5,  # pole
        6,  # traffic light
        7,  # traffic sign
        # 8,  # vegetation
        # 9,  # terrain
        # 10,  # sky
        11,  # car
        12,  # truck
        13,  # bus
        14,  # train
        15,  # motorcycle
        16,  # bicycle
    ]
    ignore_background: True
    eps: 2.5
    min_samples: 10
    k: 1
  experiment2:
    dataset: cityscapes_bus
    split: test
    train_dataset: cityscapes_bus
    train_split: train
    dict: experiment2_data.p
    model: deeplabv3plus_2
    init_weights: initials/experiment2/best.pth
    meta_model: gradient_boosting_2
    pred_class_selection: [
        # 0,  # road
        # 1,  # sidewalk
        # 2,  # building
        3,  # wall
        4,  # fence
        # 5,  # pole
        6,  # traffic light
        7,  # traffic sign
        # 8,  # vegetation
        # 9,  # terrain
        # 10,  # sky
        11,  # person
        12,  # rider
        13,  # car
        14,  # truck
        15,  # train
        16,  # motorcycle
        17,  # bicycle
    ]
    ignore_background: False
    eps: 2.5
    min_samples: 10
    k: 1
  experiment3:
    dataset: cityscapes_human_bus_car
    split: test
    train_dataset: cityscapes_human_bus_car
    train_split: train
    dict: experiment3_data.p
    model: deeplabv3plus_5
    init_weights: initials/experiment3/best.pth
    meta_model: gradient_boosting_5
    pred_class_selection: [
        # 0,  # road
        # 1,  # sidewalk
        # 2,  # building
        3,  # wall
        4,  # fence
        # 5,  # pole
        6,  # traffic light
        7,  # traffic sign
        # 8,  # vegetation
        # 9,  # terrain
        # 10,  # sky
        11,  # truck
        12,  # train
        13,  # motorcycle
        14,  # bicycle
    ]
    ignore_background: True
    eps: 1.75
    min_samples: 10
    k: 2
  experiment4a:
    dataset: a2d2
    split: test
    train_dataset: a2d2
    train_split: train
    dict: experiment4a_data.p
    model: deeplabv3plus_3a
    init_weights: initials/experiment4a/best.pth
    meta_model: gradient_boosting_3a
    eps: 3
    min_samples: 10
    k: 1
  experiment4b:
    dataset: a2d2
    split: test
    train_dataset: a2d2
    train_split: train
    dict: experiment4b_data.p
    model: pspnet_3b
    init_weights: initials/experiment4b/best.pth
    meta_model: gradient_boosting_3b
    ignore_background: False
    eps: 3
    min_samples: 10
    k: 1
  experiment5:
    dataset: a2d2
    split: test
    train_dataset: cityscapes
    train_split: train
    dict: experiment5_data.p
    model: deeplabv3plus_4
    init_weights: initials/experiment5/best.pth
    meta_model: gradient_boosting_4 
    ignore_background: False
    eps: 2.5
    min_samples: 10
    k: 1